name: Consul
description: >
  A single scalable consul node.
version: 0.8.5-rancher
category: Configuration
maintainer: github.com/jnovack
license: MIT
projectURL: https://github.com/jnovack/cattle-catalog
