name: Consul
description: >
  A single scalable consul node.
  # Description of the Catalog Entry
version: 0.1
category: Configuration
maintainer: github.com/jnovack
license: MIT
projectURL: https://github.com/jnovack/cattle-catalog
