version: '2'
services:
  registrator:
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: registrator-config
    tty: true
    restart: always
    entrypoint: /bin/sh -c "while [ ! -f '/certs/ssl.key' ]; do echo 'waiting for certs...'; sleep 1; done; exec registrator consul-tls://${consul_server}"
    image: jnovack/registrator:v8-alpha.2
    network_mode: "host"
    volumes:
      - /certs
      - /var/run/docker.sock:/tmp/docker.sock
    environment:
      - CONSUL_HTTP_TOKEN=${acl_token}
      - CONSUL_CACERT=/certs/ca.crt
      - CONSUL_TLSCERT=/certs/ssl.crt
      - CONSUL_TLSKEY=/certs/ssl.key

  registrator-config:
    image: registry.oz/registrator-confd:latest
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    volumes_from:
      - registrator
