version: '2'
services:
  agent:
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    tty: true
    restart: always
    command:
      - "consul-tls://${consul_server}"
    image: gliderlabs/registrator:master
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    environment:
      - CONSUL_HTTP_TOKEN=${acl_token}
      - CONSUL_CACERT=${ca_crt}
      - CONSUL_TLSCERT=${ssl_crt}
      - CONSUL_TLSKEY=${ssl_key}
