version: '2'
catalog:
  name: "Registrator"
  description: "Registrator agent for Consul cluster"
  version: "0.8-alpha.1"
  uuid: registrator-0
  questions:
    - variable: consul_server
      label: "Consul server (address:port)"
      type: "string"
      required: true
    - variable: acl_token
      label: "ACL Token"
      type: "string"
      required: true
    - variable: ssl_key
      label: "SSL Key"
      type: "multiline"
      required: true
    - variable: ssl_crt
      label: "SSL Certificate"
      type: "multiline"
      required: true
    - variable: ca_crt
      label: "CA Certificate"
      type: "multiline"
      required: true

services:
  registrator:
    metadata:
      ca: |
        ${ca_crt}
      cert: |
        ${ssl_crt}
      key: |
        ${ssl_key}