version: '2'
services:
  consul-server:
    image: consul:latest
    command: /bin/sh -c "while [ ! -f '/opt/rancher/config/server.json' ]; do echo 'waiting for /opt/rancher/config/server.json...'; sleep 1; done; exec consul agent -config-file=/opt/rancher/config/server.json"
    labels:
      io.rancher.sidekicks: consul-config
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8301:8301/udp"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - /opt/rancher/ssl
      - /opt/rancher/config
      - consul:/var/consul

  consul-config:
    image: registry.oz/consul-confd:latest
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    volumes_from:
      - consul-server
    network_mode: "container:consul-server"

  webserver:
    ports:
      - 8500
    image: rancher/lb-service-haproxy

volumes:
  consul:
    driver: rancher-nfs