config:
  image: registry.oz/consul-confd:latest
  labels:
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - server
  net: "container:server"

server:
  image: consul:latest
  command: /bin/sh -c "while [ ! -f '/opt/rancher/config/server.json' ]; do echo 'waiting for /opt/rancher/config/server.json...'; sleep 1; done; exec consul agent -config-file=/opt/rancher/config/server.json -data-dir=/var/consul"
  labels:
    io.rancher.sidekicks: config
  volumes:
    - /opt/rancher/ssl
    - /opt/rancher/config
    - /var/consul