version: '2'
catalog:
  name: "Consul"
  description: "Minimally Secure Consul cluster"
  version: "0.1"
  uuid: consul-0
  questions:
    - variable: gossip
      label: "Communication gossip key"
      type: "string"
      required: true
    - variable: ui
      label: "Enable UI"
      type: "boolean"
      default: true
      required: true
    - variable: datacenter
      label: "Datacenter Name"
      type: "string"
      required: true
      default: "dc1"
    - variable: domain
      label: "DNS Suffix"
      type: "string"
      required: true
      default: "consul"
    - variable: master_token
      label: "ACL Master Token"
      type: "string"
      required: true
    - variable: default_policy
      label: "ACL Default Policy"
      type: "enum"
      required: true
      default: "allow"
      options:
        - allow
        - deny
    - variable: ssl_key
      label: "SSL Key"
      type: "multiline"
      required: true
    - variable: ssl_crt
      label: "SSL Certificate"
      type: "multiline"
      required: true
    - variable: ca_crt
      label: "CA Certificate"
      type: "multiline"
      required: true

services:
  consul-server:
    scale: 3
    metadata:
      ui: "${ui}"
      datacenter: "${datacenter}"
      domain: "${domain}"
      gossip: "${gossip}"
      master-token: "${master_token}"
      default-policy: "${default_policy}"
      ca: |
        ${ca_crt}
      cert: |
        ${ssl_crt}
      key: |
        ${ssl_key}

  webserver:
    scale: 1
    lb_config:
      port_rules:
        - source_port: 443
          target_port: 8443
          protocol: "tcp"
          service: consul-server
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000