.catalog:
  name: "Consul"
  description: "Minimally Secure Consul cluster"
  version: "0.1"
  uuid: consul
  questions:
    - variable: gossip
      label: "Communication gossip key"
      type: "string"
      required: true
    - variable: ssl_key
      label: "SSL Key"
      type: "multiline"
      required: true
    - variable: ssl_crt
      label: "SSL Certificate"
      type: "multiline"
      required: true
    - variable: ca_crt
      label: "CA Certificate"
      type: "multiline"
      required: true
    - variable: ui
      label: "Enable UI"
      type: "boolean"
      default: true
      required: true
consul-server:
  metadata:
    ozmo: "ozmo"
    ui: "${ui}"
    gossip: "${gossip}"
