version: '2'
catalog:
  name: "Consul"
  description: "Minimally Secure Consul cluster"
  version: "0.1"
  uuid: 974DB406-D527-4D4A-80CC-B912CC65EBF6
  questions:
    - variable: gossip_key
      label: "Communication gossip key"
      type: "string"
      required: true
    - variable: ssl_key
      label: "SSL Key"
      type: "multiline"
      required: true
    - variable: ssl_crt
      label: "SSL Certificate"
      type: "multiline"
      required: true
    - variable: ca_crt
      label: "CA Certificate"
      type: "multiline"
      required: true
    - variable: ui
      label: "Enable UI"
      type: "boolean"
      default: false
      required: true
consul-server:
  metadata:
    consul-server:
      ui.enabled: ${ui}
      enc.key: "${gossip_key}"
      ca.crt: |
        ${ca_crt}
      ssl.crt: |
        ${ssl_crt}
      ssl.key: |
        ${ssl_key}